name: Feature Request
description: Suggest a new feature or improvement
title: '[Feature]: '
labels: ['enhancement', 'feature']
projects: ['octo-org/1', 'octo-org/44']
assignees:
    - octocat
body:
    - type: markdown
      attributes:
          value: |
              Thank you for suggesting a new feature! Please fill out the following form to help us understand your idea.
    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: How can we get in touch with you if we need more info?
          placeholder: ex. email@example.com
      validations:
          required: false
    - type: textarea
      id: feature-description
      attributes:
          label: Feature Description
          description: Describe the feature you'd like to see. What problem does it solve or what improvement does it bring?
          placeholder: Describe the new feature here
      validations:
          required: true
    - type: textarea
      id: motivation
      attributes:
          label: Motivation
          description: Why do you think this feature is important? How will it benefit the project?
          placeholder: Why is this feature needed?
      validations:
          required: true
    - type: textarea
      id: implementation-ideas
      attributes:
          label: Implementation Ideas
          description: Do you have any suggestions on how this feature could be implemented?
          placeholder: Share your ideas on how to implement the feature
      validations:
          required: false
    - type: dropdown
      id: priority
      attributes:
          label: Priority
          description: How would you rate the priority of this feature?
          options:
              - Low
              - Medium
              - High
          default: Low
      validations:
          required: true
    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this feature request, you agree to follow our [Code of Conduct](https://example.com)
          options:
              - label: I agree to follow this project's Code of Conduct
                required: true
