# Generated by Django 5.1.1 on 2024-11-13 01:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_system', '0002_rename_student_id_student_id_card_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('description', models.TextField()),
                ('students', models.ManyToManyField(related_name='courses', to='user_system.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_system.teacher')),
            ],
        ),
    ]
