# Generated by Django 5.1.6 on 2025-03-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "school_system",
            "0004_course_department_course_link_course_location_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
