# .github/workflows/continuous-integration-workflow.yml

# The name of the workflow which you can see when the action runs
name: Run unit tests

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Jobs will run in parallel
jobs:
  run-unit-tests:
    # This job runs on Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    # Steps run synchronously (one after the other)
    steps:
      # Retrieve the codebase on the ubuntu machine.
      # if the codebase isn't required, this step can be skipped.
      - uses: actions/checkout@v2

        # Step 2: Set up Node.js to version 21.6.2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.6.2'  # Update to Node.js version 21.6.2

      - name: Install Node.js
        run: npm ci

      - name: Run server
        run: npm run test